In [345]:
# 전처리된 기존 데이터(json) load
import pickle
import re
with open('cnt_data.pkl', 'rb') as f:
    cnt_df = pickle.load(f)
    
# 이전 데이터 load
with open("data.pkl", 'rb') as f :
        answer_data = pickle.load(f)
answer_data['contents'] = answer_data['contents'].apply(lambda x: re.sub(r'(<([^>]+)>)', '', x))

In [346]:
answer_data

,id,title_x,contents,categoryId,title_y,type
0,1217534,동물들의 눈동자 형태는 왜 다를까요?,"고양이의 눈동자는 세로형으로, 인간의 눈동자와는 다릅니다. 그렇다면 왜 동물들의 눈...",52,생활꿀팁,open
1,704727,긴장을 완화하는 방법이 있을까요?,안녕하세요 긴장이 될때 긴장을 풀수 있는 좋은 방법이 있을까요?? 아시는 분은 답변...,52,생활꿀팁,open
2,1291591,두발자전거 잘타는 방법은 무엇인지,안녕하세요 아이가 초등학생인데 아직 자전거를 못타네요 두발자전거를 가르쳐야하는데 그...,52,생활꿀팁,open
3,819047,택시 합승은 불법적인 행위인가요?,택시를 타게 되면 합승을 해도 되냐고 운전기사분이 물어보시는데요.솔직히 바빠서 택시...,52,생활꿀팁,open
4,989838,물티슈에 묻어나오는 물은 정말 그냥 물인가요?,안녕하세요물티슈를 자주사용하는 사람입니다물티슈를 꺼내어 사용하면 물이 묻어나오는데말...,52,생활꿀팁,open
...,...,...,...,...,...,...
458334,1555903,두통이 자꾸만 지속이되고있어요,제가 요즘 두통이 자꾸만 지속이 되어서 두통약도 지어먹어 보고 다른 방법도 써봤는데...,101,한방,expert
458335,1194529,땀이 많은 체질이 개선이 가능한가요,저는 다른 사람에 비해 땀이 많이 나는 편입니다이렇게 땀이 많은 체질이 개선이 가능...,101,한방,expert
458336,1446789,와이프가 당뇨 판정을 받았습니다. 한방쪽으로도 병행해서 치료를 받았으면 하는데 어떤...,와이프가 얼마전 당뇨 판정을 받았습니다. 몸에 부담가지 않는선에서 한방쪽으로도 병행...,101,한방,expert
458337,1561127,객담도 한방치료가 가능한가 요?,담배를 피우다보니 객담이 많이 나오는거 같아서 한방치료를 받아볼까하는데 어떤치료가 ...,101,한방,expert
458338,1192020,눈 밑 꺼짐과 다크서클 없애는 방법 있나요?,작년부터 눈 밑 꺼짐과 다크서클이 너무 심한대요.화장해도 보일정도입니다.한약이나 침...,101,한방,expert

In [361]:
from tqdm import tqdm
import pandas as pd

answer_data_querys = answer_data['contents'].tolist()
answer_data_title = answer_data['title_y'].tolist()
evaluation_df = pd.DataFrame({'answer_data_querys' : answer_data_querys, 'answer_title' : answer_data_title},columns=['answer_data_querys', 'predict_KoparentId', 'answer_title'])
# 클래스별 개 

sampled_data = pd.concat([group.head(100) for i, group in evaluation_df.groupby('answer_title')])

sampled_data.reset_index(drop=True, inplace=True)
sampled_data['answer_title'].value_counts()
sampled_data['Bool'] = False

In [362]:
sampled_data

,answer_data_querys,predict_KoparentId,answer_title,Bool
0,요즘 테슬라 하면 머스크 얘기가 많이 나오던데 테슬라 요건이란 용어를 보았습니다. ...,NaN,경제·금융,False
1,현재 하나은행 신용카드를 사용하고 있는데 카드 유효기간이 2023년 6월에 만료가 ...,NaN,경제·금융,False
2,"채권을 공부하고 있는데, 유로채라는게 있고, 유로채는 Bearer Bond라고 합니...",NaN,경제·금융,False
3,제로금리라는 말이있는데분명히 대출이자가 0프라는말은 아닐텐데요 질문드립니다.제로금리...,NaN,경제·금융,False
4,안녕하세요현재 미국의 재정때문에 디폴트 선언까지나오는데요 정말 위험한수준인건가요?미...,NaN,경제·금융,False
...,...,...,...,...
2495,최근에 발목을 접질러서 인대를 다친 것 같습니다ㅜㅠ쩔뚝 거리면서 걷는데 너무 아프네...,NaN,한방,False
2496,안녕하세요 한약을 먹을 때 무와 돼지고기를 피하라고 하더라구요.왜 돼지고기를 웬만하...,NaN,한방,False
2497,한방에서 사람 인체의 오장육부와 신맛 쓴맛 등 맛과 관계가 있다고 하는데요 한방에서...,NaN,한방,False
2498,다이어트 한약 복용을 하고 싶은데 지방간인 경우 아예 한약 복용이 안되는 건지 궁금...,NaN,한방,False
2499,고협압 당뇨가 있는데 한방처방 가능 한건가요지금은 꾸준히 운동하는데 처방 으로 수치...,NaN,한방,False

In [363]:
# 카테고리 재 맵핑
answer_list = {
    "answer_title" : ['캠핑', '과학', '생활꿀팁', '영양・식단', '청소', '재무설계', '고민 상담', '교통사고', '무역', '의료', '육아·아동', '반려동물', '한방', '자동차', '등산', '법률', '경제·금융', '인문·예술', '부동산', '세탁', '인사·노무', '보험', '치과', '약료', '세금·세무'],
    "KoparentId" : ['취미여가활동', '학문', '생활', '건강관리', '생활', '경제', '고민상담', '법률', '경제', '건강상담', '육아', '반려동물', '약영양제', '생활', '취미여가활동', '법률', '경제', '학문', '경제', '생활', '고용노동', '보험', '건강상담', '약영양제', '세금세무']
}
tmp_df = pd.DataFrame(answer_list)
sampled_data = pd.merge(sampled_data, tmp_df, on='answer_title', how='inner')

In [364]:
sampled_data = sampled_data[['answer_data_querys', 'predict_KoparentId', 'answer_title', 'KoparentId', 'Bool']]
sampled_data.drop("answer_title", axis=1, inplace=True)
sampled_data

,answer_data_querys,predict_KoparentId,KoparentId,Bool
0,요즘 테슬라 하면 머스크 얘기가 많이 나오던데 테슬라 요건이란 용어를 보았습니다. ...,NaN,경제,False
1,현재 하나은행 신용카드를 사용하고 있는데 카드 유효기간이 2023년 6월에 만료가 ...,NaN,경제,False
2,"채권을 공부하고 있는데, 유로채라는게 있고, 유로채는 Bearer Bond라고 합니...",NaN,경제,False
3,제로금리라는 말이있는데분명히 대출이자가 0프라는말은 아닐텐데요 질문드립니다.제로금리...,NaN,경제,False
4,안녕하세요현재 미국의 재정때문에 디폴트 선언까지나오는데요 정말 위험한수준인건가요?미...,NaN,경제,False
...,...,...,...,...
2495,최근에 발목을 접질러서 인대를 다친 것 같습니다ㅜㅠ쩔뚝 거리면서 걷는데 너무 아프네...,NaN,약영양제,False
2496,안녕하세요 한약을 먹을 때 무와 돼지고기를 피하라고 하더라구요.왜 돼지고기를 웬만하...,NaN,약영양제,False
2497,한방에서 사람 인체의 오장육부와 신맛 쓴맛 등 맛과 관계가 있다고 하는데요 한방에서...,NaN,약영양제,False
2498,다이어트 한약 복용을 하고 싶은데 지방간인 경우 아예 한약 복용이 안되는 건지 궁금...,NaN,약영양제,False
2499,고협압 당뇨가 있는데 한방처방 가능 한건가요지금은 꾸준히 운동하는데 처방 으로 수치...,NaN,약영양제,False

In [382]:
from sentence_transformers import SentenceTransformer, util
import pickle
import numpy as np
import pickle
from annoy import AnnoyIndex
import time

# 임베딩 값 불러오기
# embedder = SentenceTransformer('jhgan/ko-sroberta-multitask')
# embedder = SentenceTransformer('smartmind/ko-sbert-augSTS-maxlength512')
# embedder = SentenceTransformer('intfloat/multilingual-e5-base')
# embedder = SentenceTransformer('ddobokki/unsup-simcse-klue-roberta-small')
embedder = SentenceTransformer('sentence-transformers/facebook-dpr-ctx_encoder-single-nq-base')

embedding_start = time.time()
sentences = cnt_df['content'].tolist()
corpus_embeddings = embedder.encode(sentences, convert_to_tensor=True)

vector_size = 768  # Length of item vector that will be indexed

metric_list = ['angular', 'euclidean', 'manhattan', 'hamming', 'dot']
for metric in metric_list:
    annoy_index = AnnoyIndex(vector_size, metric=metric)


    for idx in range(cnt_df.shape[0]):
        
        vector = corpus_embeddings[idx]
        annoy_index.add_item(idx, vector)

    annoy_index.build(10) # 10 trees
    annoy_index.save(f'/Users/seunghyun/anaconda3/envs/my_env/23.09.25/ann/sentence_transformers/topic_classify_{metric}.ann')

* 기존 ver1 테스트 코드

In [384]:
import time
from annoy import AnnoyIndex
import pickle
from sentence_transformers import SentenceTransformer, util

embedder = SentenceTransformer('jhgan/ko-sroberta-multitask')
# # embedder = SentenceTransformer('smartmind/ko-sbert-augSTS-maxlength512')
# # embedder = SentenceTransformer('intfloat/multilingual-e5-base')
# # embedder = SentenceTransformer('ddobokki/unsup-simcse-klue-roberta-small')
# # embedder = SentenceTransformer('sentence-transformers/facebook-dpr-ctx_encoder-single-nq-base')


with open("cnt_data.pkl", 'rb') as f:
    cnt_df = pickle.load(f)
vector_size = 768


annoy_index = AnnoyIndex(vector_size, 'angular')

start_time = time.time()

queries = """현재 15만원 일당 돈을 3.3원천징수 후
제 통장으로 세명분의 월급을 받고있습니다.
<본인포함 팀원 모두 15만원>
현재 소득이 6800만원정도가 계산되는데
실질적으로 제가 받는 돈은 제가 일 한 몫 과 팀원들 식비 차비 등 일하면서 썻던 돈을 다시 돌려받는데,<제 돈으로 일단내고 회사에 청구> 소득이 너무 많이 잡히게될 것 같아 질문드립니다.
원천세 신고를 해야 하는건가요?<이 경우 3.3% 또 떼야하는데 저는 똑같은 돈 받는 사람일뿐..>
대리 수령인으로 해야하는건가요?"""

# queries = """"""

queries = [queries]
annoy_index.load(f'/Users/seunghyun/anaconda3/envs/my_env/23.09.25/ann/jhgan/topic_classify_angular.ann')
# 3개만 출력
top_k = 3
for query in queries:
    query_embedding = embedder.encode(query, convert_to_tensor=True)

    top_results = annoy_index.get_nns_by_vector(query_embedding, top_k, include_distances=True)

    end_time = time.time()
    
    print("\n======================\n")
    print("검색어: ", query)
    print(f" {metric} 검색결과 : {top_k}개 출력")
    print("\n======================\n")
    ko_list = []
    title_list = []
    for idx, distance in zip(top_results[0], top_results[1]):
        print(f"중분류 : {cnt_df['KoparentId'].iloc[idx]} | 소분류 : {cnt_df['title'].iloc[idx]} | {metric} distance : {round(distance,4)}")    
        ko_list.append(cnt_df['KoparentId'].iloc[idx])
        title_list.append(cnt_df['title'].iloc[idx])
    print(" ")
    search_time = end_time - start_time
    print(ko_list)
    print(title_list)
    print(f"검색 시간: {search_time:.4f} 초")
    
# annoy, 지표, 모듈화

======================

검색어:  현재 15만원 일당 돈을 3.3원천징수 후
제 통장으로 세명분의 월급을 받고있습니다.
<본인포함 팀원 모두 15만원>
현재 소득이 6800만원정도가 계산되는데
실질적으로 제가 받는 돈은 제가 일 한 몫 과 팀원들 식비 차비 등 일하면서 썻던 돈을 다시 돌려받는데,<제 돈으로 일단내고 회사에 청구> 소득이 너무 많이 잡히게될 것 같아 질문드립니다.
원천세 신고를 해야 하는건가요?<이 경우 3.3% 또 떼야하는데 저는 똑같은 돈 받는 사람일뿐..>
대리 수령인으로 해야하는건가요?
 dot 검색결과 : 3개 출력

======================

중분류 : 세금세무 | 소분류 : 종합소득세 | dot distance : 0.9174
중분류 : 고용노동 | 소분류 : 임금체불 | dot distance : 0.9456
중분류 : 고용노동 | 소분류 : 산업재해 | dot distance : 0.9686

['세금세무', '고용노동', '고용노동']
['종합소득세', '임금체불', '산업재해']
검색 시간: 0.0801 초

* 지표 추출

In [367]:
import time
from annoy import AnnoyIndex
import pickle
from sentence_transformers import SentenceTransformer, util

embedder = SentenceTransformer('jhgan/ko-sroberta-multitask')

metric = ['', , , , , ]

with open("cnt_data.pkl", 'rb') as f:
    cnt_df = pickle.load(f)

vector_size = 768
annoy_index = AnnoyIndex(vector_size, metric)

start_time = time.time()


queries = [queries]
annoy_index.load(f'/Users/seunghyun/anaconda3/envs/my_env/23.09.25/ann/jhgan/topic_classify_' + metric +'.ann')

KoparentId_list = []
title_list = []
distance_list = []
    

def start(queries) :
    
    # 3개만 출력
    top_k = 3
    for query in queries:
        query_embedding = embedder.encode(query, convert_to_tensor=True)

        top_results = annoy_index.get_nns_by_vector(query_embedding, top_k, include_distances=True)

        end_time = time.time()
        for idx, distance in zip(top_results[0], top_results[1]):
            KoparentId_list.append(cnt_df['KoparentId'].iloc[idx])
            title_list.append(cnt_df['title'].iloc[idx])
            distance_list.append(round(distance,4))
        search_time = end_time - start_time
        global result_df
        result_df = pd.DataFrame({'KoparentId': KoparentId_list, "title": title_list, f'{metric}_distance': distance_list})
        
        
        # annoy, 지표, 모듈화

In [368]:
sampled_data

,answer_data_querys,predict_KoparentId,KoparentId,Bool
0,요즘 테슬라 하면 머스크 얘기가 많이 나오던데 테슬라 요건이란 용어를 보았습니다. ...,NaN,경제,False
1,현재 하나은행 신용카드를 사용하고 있는데 카드 유효기간이 2023년 6월에 만료가 ...,NaN,경제,False
2,"채권을 공부하고 있는데, 유로채라는게 있고, 유로채는 Bearer Bond라고 합니...",NaN,경제,False
3,제로금리라는 말이있는데분명히 대출이자가 0프라는말은 아닐텐데요 질문드립니다.제로금리...,NaN,경제,False
4,안녕하세요현재 미국의 재정때문에 디폴트 선언까지나오는데요 정말 위험한수준인건가요?미...,NaN,경제,False
...,...,...,...,...
2495,최근에 발목을 접질러서 인대를 다친 것 같습니다ㅜㅠ쩔뚝 거리면서 걷는데 너무 아프네...,NaN,약영양제,False
2496,안녕하세요 한약을 먹을 때 무와 돼지고기를 피하라고 하더라구요.왜 돼지고기를 웬만하...,NaN,약영양제,False
2497,한방에서 사람 인체의 오장육부와 신맛 쓴맛 등 맛과 관계가 있다고 하는데요 한방에서...,NaN,약영양제,False
2498,다이어트 한약 복용을 하고 싶은데 지방간인 경우 아예 한약 복용이 안되는 건지 궁금...,NaN,약영양제,False
2499,고협압 당뇨가 있는데 한방처방 가능 한건가요지금은 꾸준히 운동하는데 처방 으로 수치...,NaN,약영양제,False

In [369]:
# # 리팩토링 해야함
# sentence = sampled_data['answer_data_querys'].tolist()
# metric_list = ['angular', 'euclidean', 'manhattan', 'hamming', 'dot']
# sampled_data['distance'] = None
# for metric in tqdm(metric_list):
#     for idx, queries in enumerate(sentence):
        
#         start(queries, metric)
#         sampled_data.at[idx,'predict_KoparentId'] = result_df['KoparentId'].tolist()
#         sampled_data.at[idx,'distance'] = result_df[f'{metric}_distance'].tolist()
        
#     globals()[f"real_{metric}_sampled_data"] = sampled_data

In [370]:
sentence = sampled_data['answer_data_querys'].tolist()

In [385]:
result_df

  KoparentId     title  dot_distance
0       약영양제      약 복용       58.6780
1       약영양제        한약       57.7404
2       건강관리  식습관·식이요법       57.0190

In [371]:
metric = 'angular'
sampled_data['distance'] = None
for idx, queries in enumerate(sentence):
        
    start(queries, metric)
    
    sampled_data.at[idx,'predict_KoparentId'] = result_df['KoparentId'].tolist()
    sampled_data.at[idx,'distance'] = result_df[f'{metric}_distance'].tolist()
angular_sampled_data = sampled_data
real_angular_sampled_data = angular_sampled_data.copy()
real_angular_sampled_data

,answer_data_querys,predict_KoparentId,KoparentId,Bool,distance
0,요즘 테슬라 하면 머스크 얘기가 많이 나오던데 테슬라 요건이란 용어를 보았습니다. ...,"[고용노동, 법률, AMA]",경제,False,"[1.1995, 1.2144, 1.2171]"
1,현재 하나은행 신용카드를 사용하고 있는데 카드 유효기간이 2023년 6월에 만료가 ...,"[경제, 경제, 법률]",경제,False,"[1.1434, 1.1448, 1.1652]"
2,"채권을 공부하고 있는데, 유로채라는게 있고, 유로채는 Bearer Bond라고 합니...","[경제, 경제, 법률]",경제,False,"[0.9719, 1.0106, 1.0613]"
3,제로금리라는 말이있는데분명히 대출이자가 0프라는말은 아닐텐데요 질문드립니다.제로금리...,"[경제, 경제, 경제]",경제,False,"[1.0715, 1.0768, 1.1345]"
4,안녕하세요현재 미국의 재정때문에 디폴트 선언까지나오는데요 정말 위험한수준인건가요?미...,"[법률, 심리, 고용노동]",경제,False,"[1.0474, 1.1023, 1.1075]"
...,...,...,...,...,...
2495,최근에 발목을 접질러서 인대를 다친 것 같습니다ㅜㅠ쩔뚝 거리면서 걷는데 너무 아프네...,"[건강상담, 건강상담, 건강상담]",약영양제,False,"[0.9355, 0.9545, 0.9925]"
2496,안녕하세요 한약을 먹을 때 무와 돼지고기를 피하라고 하더라구요.왜 돼지고기를 웬만하...,"[건강관리, 약영양제, 약영양제]",약영양제,False,"[1.0679, 1.0889, 1.121]"
2497,한방에서 사람 인체의 오장육부와 신맛 쓴맛 등 맛과 관계가 있다고 하는데요 한방에서...,"[약영양제, 건강관리, 약영양제]",약영양제,False,"[0.9365, 1.0184, 1.031]"
2498,다이어트 한약 복용을 하고 싶은데 지방간인 경우 아예 한약 복용이 안되는 건지 궁금...,"[건강관리, 약영양제, 건강관리]",약영양제,False,"[0.9156, 0.9305, 0.9506]"
2499,고협압 당뇨가 있는데 한방처방 가능 한건가요지금은 꾸준히 운동하는데 처방 으로 수치...,"[건강관리, 건강관리, 약영양제]",약영양제,False,"[0.9601, 0.9702, 0.9739]"

In [372]:
metric = 'euclidean'
sampled_data['distance'] = None
for idx, queries in enumerate(sentence):
        
    start(queries, metric)
    
    sampled_data.at[idx,'predict_KoparentId'] = result_df['KoparentId'].tolist()
    sampled_data.at[idx,'distance'] = result_df[f'{metric}_distance'].tolist()
euclidean_sampled_data = sampled_data
real_euclidean_sampled_data = euclidean_sampled_data.copy()
real_euclidean_sampled_data

,answer_data_querys,predict_KoparentId,KoparentId,Bool,distance
0,요즘 테슬라 하면 머스크 얘기가 많이 나오던데 테슬라 요건이란 용어를 보았습니다. ...,"[법률, 고용노동, 경제]",경제,False,"[12.3679, 12.3863, 12.5663]"
1,현재 하나은행 신용카드를 사용하고 있는데 카드 유효기간이 2023년 6월에 만료가 ...,"[법률, 경제, 경제]",경제,False,"[11.4572, 11.4988, 11.8616]"
2,"채권을 공부하고 있는데, 유로채라는게 있고, 유로채는 Bearer Bond라고 합니...","[경제, 경제, 법률]",경제,False,"[10.1474, 10.6123, 10.8925]"
3,제로금리라는 말이있는데분명히 대출이자가 0프라는말은 아닐텐데요 질문드립니다.제로금리...,"[경제, 경제, 경제]",경제,False,"[10.9455, 11.4432, 11.5142]"
4,안녕하세요현재 미국의 재정때문에 디폴트 선언까지나오는데요 정말 위험한수준인건가요?미...,"[법률, 보험, 심리]",경제,False,"[11.4529, 11.8915, 12.0042]"
...,...,...,...,...,...
2495,최근에 발목을 접질러서 인대를 다친 것 같습니다ㅜㅠ쩔뚝 거리면서 걷는데 너무 아프네...,"[건강상담, 건강상담, 건강상담]",약영양제,False,"[9.3604, 9.4455, 9.9107]"
2496,안녕하세요 한약을 먹을 때 무와 돼지고기를 피하라고 하더라구요.왜 돼지고기를 웬만하...,"[건강관리, 건강관리, 약영양제]",약영양제,False,"[10.6633, 11.4621, 11.4784]"
2497,한방에서 사람 인체의 오장육부와 신맛 쓴맛 등 맛과 관계가 있다고 하는데요 한방에서...,"[약영양제, 건강관리, 건강관리]",약영양제,False,"[10.25, 11.0023, 11.0384]"
2498,다이어트 한약 복용을 하고 싶은데 지방간인 경우 아예 한약 복용이 안되는 건지 궁금...,"[건강관리, 건강관리, 약영양제]",약영양제,False,"[9.6561, 9.8079, 10.0699]"
2499,고협압 당뇨가 있는데 한방처방 가능 한건가요지금은 꾸준히 운동하는데 처방 으로 수치...,"[건강관리, 건강상담, 건강관리]",약영양제,False,"[9.4005, 10.0248, 10.0988]"

In [373]:
metric = 'manhattan'
sampled_data['distance'] = None
for idx, queries in enumerate(sentence):
        
    start(queries, metric)
    
    sampled_data.at[idx,'predict_KoparentId'] = result_df['KoparentId'].tolist()
    sampled_data.at[idx,'distance'] = result_df[f'{metric}_distance'].tolist()
manhattan_sampled_data = sampled_data
real_manhattan_sampled_data = manhattan_sampled_data.copy()
real_manhattan_sampled_data

,answer_data_querys,predict_KoparentId,KoparentId,Bool,distance
0,요즘 테슬라 하면 머스크 얘기가 많이 나오던데 테슬라 요건이란 용어를 보았습니다. ...,"[고용노동, 법률, 경제]",경제,False,"[274.9782, 275.7122, 276.4165]"
1,현재 하나은행 신용카드를 사용하고 있는데 카드 유효기간이 2023년 6월에 만료가 ...,"[경제, 법률, 경제]",경제,False,"[256.0587, 256.0866, 260.588]"
2,"채권을 공부하고 있는데, 유로채라는게 있고, 유로채는 Bearer Bond라고 합니...","[경제, 경제, 법률]",경제,False,"[224.8525, 232.544, 239.8088]"
3,제로금리라는 말이있는데분명히 대출이자가 0프라는말은 아닐텐데요 질문드립니다.제로금리...,"[경제, 경제, 경제]",경제,False,"[239.8244, 253.4214, 256.274]"
4,안녕하세요현재 미국의 재정때문에 디폴트 선언까지나오는데요 정말 위험한수준인건가요?미...,"[법률, 보험, 경제]",경제,False,"[254.4191, 264.2781, 266.6864]"
...,...,...,...,...,...
2495,최근에 발목을 접질러서 인대를 다친 것 같습니다ㅜㅠ쩔뚝 거리면서 걷는데 너무 아프네...,"[건강상담, 건강상담, 건강상담]",약영양제,False,"[211.1968, 213.418, 220.3704]"
2496,안녕하세요 한약을 먹을 때 무와 돼지고기를 피하라고 하더라구요.왜 돼지고기를 웬만하...,"[건강관리, 약영양제, 건강관리]",약영양제,False,"[237.9518, 253.5032, 254.2981]"
2497,한방에서 사람 인체의 오장육부와 신맛 쓴맛 등 맛과 관계가 있다고 하는데요 한방에서...,"[약영양제, 건강관리, 건강상담]",약영양제,False,"[227.8174, 244.0246, 245.3347]"
2498,다이어트 한약 복용을 하고 싶은데 지방간인 경우 아예 한약 복용이 안되는 건지 궁금...,"[건강관리, 건강관리, 약영양제]",약영양제,False,"[213.5439, 217.0519, 220.5515]"
2499,고협압 당뇨가 있는데 한방처방 가능 한건가요지금은 꾸준히 운동하는데 처방 으로 수치...,"[건강관리, 건강상담, 약영양제]",약영양제,False,"[208.2122, 221.5114, 222.7744]"

In [374]:
metric = 'hamming'
sampled_data['distance'] = None
for idx, queries in enumerate(sentence):
        
    start(queries, metric)
    
    sampled_data.at[idx,'predict_KoparentId'] = result_df['KoparentId'].tolist()
    sampled_data.at[idx,'distance'] = result_df[f'{metric}_distance'].tolist()
hamming_sampled_data = sampled_data
real_hamming_sampled_data = hamming_sampled_data.copy()
real_hamming_sampled_data

,answer_data_querys,predict_KoparentId,KoparentId,Bool,distance
0,요즘 테슬라 하면 머스크 얘기가 많이 나오던데 테슬라 요건이란 용어를 보았습니다. ...,"[취미여가활동, 심리, 법률]",경제,False,"[88.0, 96.0, 98.0]"
1,현재 하나은행 신용카드를 사용하고 있는데 카드 유효기간이 2023년 6월에 만료가 ...,"[건강상담, 디지털가전제품, 경제]",경제,False,"[85.0, 87.0, 88.0]"
2,"채권을 공부하고 있는데, 유로채라는게 있고, 유로채는 Bearer Bond라고 합니...","[경제, 보험, 법률]",경제,False,"[83.0, 95.0, 99.0]"
3,제로금리라는 말이있는데분명히 대출이자가 0프라는말은 아닐텐데요 질문드립니다.제로금리...,"[경제, 심리, 경제]",경제,False,"[87.0, 91.0, 93.0]"
4,안녕하세요현재 미국의 재정때문에 디폴트 선언까지나오는데요 정말 위험한수준인건가요?미...,"[법률, 경제, 고용노동]",경제,False,"[94.0, 96.0, 105.0]"
...,...,...,...,...,...
2495,최근에 발목을 접질러서 인대를 다친 것 같습니다ㅜㅠ쩔뚝 거리면서 걷는데 너무 아프네...,"[건강상담, 스포츠운동, 심리]",약영양제,False,"[84.0, 87.0, 91.0]"
2496,안녕하세요 한약을 먹을 때 무와 돼지고기를 피하라고 하더라구요.왜 돼지고기를 웬만하...,"[건강관리, 건강관리, 스포츠운동]",약영양제,False,"[76.0, 80.0, 87.0]"
2497,한방에서 사람 인체의 오장육부와 신맛 쓴맛 등 맛과 관계가 있다고 하는데요 한방에서...,"[건강상담, 건강상담, 디지털가전제품]",약영양제,False,"[88.0, 91.0, 95.0]"
2498,다이어트 한약 복용을 하고 싶은데 지방간인 경우 아예 한약 복용이 안되는 건지 궁금...,"[건강상담, 약영양제, 디지털가전제품]",약영양제,False,"[85.0, 90.0, 91.0]"
2499,고협압 당뇨가 있는데 한방처방 가능 한건가요지금은 꾸준히 운동하는데 처방 으로 수치...,"[건강관리, 스포츠운동, 심리]",약영양제,False,"[71.0, 78.0, 90.0]"

In [375]:
metric = 'dot'
sampled_data['distance'] = None
for idx, queries in enumerate(sentence):
        
    start(queries, metric)
    
    sampled_data.at[idx,'predict_KoparentId'] = result_df['KoparentId'].tolist()
    sampled_data.at[idx,'distance'] = result_df[f'{metric}_distance'].tolist()
dot_sampled_data = sampled_data
real_dot_sampled_data = dot_sampled_data.copy()
real_dot_sampled_data

,answer_data_querys,predict_KoparentId,KoparentId,Bool,distance
0,요즘 테슬라 하면 머스크 얘기가 많이 나오던데 테슬라 요건이란 용어를 보았습니다. ...,"[AMA, 고용노동, 자격증]",경제,False,"[30.3025, 29.8821, 28.6371]"
1,현재 하나은행 신용카드를 사용하고 있는데 카드 유효기간이 2023년 6월에 만료가 ...,"[경제, 경제, 법률]",경제,False,"[37.372, 34.6465, 33.3496]"
2,"채권을 공부하고 있는데, 유로채라는게 있고, 유로채는 Bearer Bond라고 합니...","[경제, 경제, 보험]",경제,False,"[57.4388, 53.9289, 47.9517]"
3,제로금리라는 말이있는데분명히 대출이자가 0프라는말은 아닐텐데요 질문드립니다.제로금리...,"[경제, 경제, 경제]",경제,False,"[47.0396, 44.4088, 36.7076]"
4,안녕하세요현재 미국의 재정때문에 디폴트 선언까지나오는데요 정말 위험한수준인건가요?미...,"[법률, 고용노동, 심리]",경제,False,"[53.9021, 50.9314, 46.4546]"
...,...,...,...,...,...
2495,최근에 발목을 접질러서 인대를 다친 것 같습니다ㅜㅠ쩔뚝 거리면서 걷는데 너무 아프네...,"[건강상담, 건강상담, 건강상담]",약영양제,False,"[57.07, 52.3533, 51.4156]"
2496,안녕하세요 한약을 먹을 때 무와 돼지고기를 피하라고 하더라구요.왜 돼지고기를 웬만하...,"[약영양제, 약영양제, 건강관리]",약영양제,False,"[44.9425, 43.1786, 42.8525]"
2497,한방에서 사람 인체의 오장육부와 신맛 쓴맛 등 맛과 관계가 있다고 하는데요 한방에서...,"[약영양제, 약영양제, 건강관리]",약영양제,False,"[67.2658, 59.0717, 56.5615]"
2498,다이어트 한약 복용을 하고 싶은데 지방간인 경우 아예 한약 복용이 안되는 건지 궁금...,"[건강관리, 약영양제, 약영양제]",약영양제,False,"[66.6393, 66.3471, 62.7967]"
2499,고협압 당뇨가 있는데 한방처방 가능 한건가요지금은 꾸준히 운동하는데 처방 으로 수치...,"[약영양제, 약영양제, 건강관리]",약영양제,False,"[58.678, 57.7404, 57.019]"

In [376]:
# 데이터 250 500 2500, 5000 기준으로 지표를 다뽑아봄

distance_df_list = [real_angular_sampled_data, real_euclidean_sampled_data, real_manhattan_sampled_data, real_hamming_sampled_data, real_dot_sampled_data]
metric_list = ['angular', 'euclidean', 'manhattan', 'hamming', 'dot']


for data in distance_df_list:

    eval_data = data
    for idx in range(len(eval_data)) :
        if eval_data['KoparentId'].iloc[idx] in eval_data['predict_KoparentId'].iloc[idx]:
            data.at[idx,'Bool'] = True



score = []        
for data in distance_df_list:
    score.append(round(len(data[data['Bool'] == True]) / len(data), 2))
final_eval_df2500 = pd.DataFrame({'metric' : metric_list, 'score' : score})

In [ ]:
# 250개의 데이터로 검증
final_eval_df250.T

              0          1          2        3     4
metric  angular  euclidean  manhattan  hamming   dot
score      0.67       0.64       0.63     0.36  0.66

In [ ]:
# 500개의 데이터로 검증
final_eval_df500.T

              0          1          2        3     4
metric  angular  euclidean  manhattan  hamming   dot
score      0.72       0.68       0.68     0.35  0.71

In [378]:
# 2500개의 데이터로 검증
final_eval_df2500.T

              0          1          2        3     4
metric  angular  euclidean  manhattan  hamming   dot
score      0.72       0.69       0.69     0.36  0.71

In [344]:
# 5000개의 데이터로 검증
final_eval_df5000.T

              0          1          2        3     4
metric  angular  euclidean  manhattan  hamming   dot
score      0.72       0.69       0.69     0.36  0.71

---

In [ ]:

eval_data =jhgan_manhattan_sampled_data
eval_data['Bool'] = False

for idx in range(len(sampled_data)):
    if eval_data['answer_title'].iloc[idx] in eval_data['predict_title'].iloc[idx]:
        eval_data.at[idx,'Bool'] = True

In [ ]:
import time
from annoy import AnnoyIndex
import pickle
from sentence_transformers import SentenceTransformer, util
from sklearn.preprocessing import minmax_scale

def start(queries=queries, metric=metric, embedder=embedder, model=model):
    with open("cnt_data.pkl", 'rb') as f:
        cnt_df = pickle.load(f)
    vector_size = 768
    annoy_index = AnnoyIndex(vector_size, metric)
    start_time = time.time()


    queries = [queries]
    
    annoy_index.load('/Users/seunghyun/anaconda3/envs/my_env/23.09.25/ann/' + model + '/topic_classify_' + metric +'.ann')
    
    # 3개만 출력
    KoparentId_list = []
    title_list = []
    distance_list = []
    top_k = 3
    for query in queries:
        query_embedding = embedder.encode(query, convert_to_tensor=True)
            
        top_results = annoy_index.get_nns_by_vector(query_embedding, top_k, include_distances=True)

        end_time = time.time()

        for idx, distance in zip(top_results[0], top_results[1]):
            
            KoparentId_list.append(cnt_df['KoparentId'].iloc[idx])
            title_list.append(cnt_df['title'].iloc[idx])
            distance_list.append(round(distance,4))
        
            
        search_time = end_time - start_time

        
        global result_df
        result_df = pd.DataFrame({'KoparentId': KoparentId_list, "title": title_list, f'{metric}_distance': distance_list})
        # result_df[f'{metric}_distance'] = minmax_scale(result_df[f'{metric}_distance'])
    # return print(cnt_df['KoparentId'].iloc[idx])